name = "getkkul-shopping"
compatibility_date = "2024-08-20"

[env.production]
name = "getkkul-shopping"

# Pages 설정
pages_build_output_dir = ".next"

# 환경 변수 (실제 값은 Cloudflare 대시보드에서 설정)
[env.production.vars]
NODE_ENV = "production"
